// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccpdiiavqojbauytnsbu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjcGRpaWF2cW9qYmF1eXRuc2J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMTkxNDgsImV4cCI6MjA1OTY5NTE0OH0.RvNllWfkRDiWodz7UyY7q6hBJNNUfwO5iRpLtW14S0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);